=== MNXOnline/drafted_models/TouristProfile_2023_06_07_12_41/schema.json
{
        "$schema": "http://json-schema.org/schema#",
        "$schemaVersion": "0.0.1",
        "$id": "https://smart-data-models.github.io/dataModel.TouristProfile/TouristProfile/schema.json,",
        "title": "General profile of a Tourist",
        "description": "Description of a tourist profile based on the characteristics of a person, trip, choice of stay and spending while in destination.",
        "modelTags": "",
        "derivedFrom": "",
        "required": [
                "id",
                "type"
        ],
        "license": "https://smart-data-models.github.io/dataModel.TouristProfile/TouristProfile/LICENSE.md",
        "type": "object",
        "properties": {
                "id": {
                        "type": "string",
                        "format": "uri"
                },
                "type": {
                        "type": "string"
                },
                "country": {
                        "type": "string",
                        "description": "Property. country of nationality - https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2"
                },
                "ageRange": {
                        "type": "object",
                        "description": "Property. age range of the person profiled",
                        "properties": {
                                "range": {
                                        "type": "string"
                                },
                                "sortingOrder": {
                                        "type": "array",
                                        "items": {
                                                "type": "string"
                                        }
                                }
                        }
                },
                "gender": {
                        "type": "string",
                        "description": "Property. gender of the person profiled"
                },
                "travelPartyComposition": {
                        "type": "string",
                        "description": "Property. composition of the travelling party based on the number of adults and children"
                },
                "lodgingType": {
                        "type": "string",
                        "description": "Property. usual type of lodging for the stay"
                },
                "lodgingCategory": {
                        "type": "string",
                        "description": "Property. usual category of the lodging"
                },
                "lodgingSize": {
                        "type": "object",
                        "description": "Property. range size in number of rooms of the lodging",
                        "properties": {
                                "range": {
                                        "type": "string"
                                },
                                "sortingOrder": {
                                        "type": "array",
                                        "items": {
                                                "type": "string"
                                        }
                                }
                        }
                },
                "roomOfStayType": {
                        "type": "string",
                        "description": "Property. usual type of the accomodation room reserved"
                },
                "board": {
                        "type": "string",
                        "description": "Property. usual type of board type reserved"
                },
                "bookingChannel": {
                        "type": "string",
                        "description": "Property. channel used by the tourist for the reservation"
                },
                "reservationLeadTime": {
                        "type": "object",
                        "description": "Property. range of days between booking and check-in",
                        "properties": {
                                "range": {
                                        "type": "string"
                                },
                                "sortingOrder": {
                                        "type": "array",
                                        "items": {
                                                "type": "string"
                                        }
                                }
                        }
                },
                "stayLength": {
                        "type": "object",
                        "description": "Property. range of number of staying nights",
                        "properties": {
                                "range": {
                                        "type": "string"
                                },
                                "sortingOrder": {
                                        "type": "array",
                                        "items": {
                                                "type": "string"
                                        }
                                }
                        }
                },
                "totalExpenditure": {
                        "type": "object",
                        "description": "Property. range of total amount of money invoiced by the lodging establishment",
                        "properties": {
                                "range": {
                                        "type": "string"
                                },
                                "sortingOrder": {
                                        "type": "array",
                                        "items": {
                                                "type": "string"
                                        }
                                }
                        }
                },
                "totalAccomodationAndBoardExpenditure": {
                        "type": "object",
                        "description": "Property. range of total amount of money invoiced by the lodging establishment in accomodation and board concepts",
                        "properties": {
                                "range": {
                                        "type": "string"
                                },
                                "sortingOrder": {
                                        "type": "array",
                                        "items": {
                                                "type": "string"
                                        }
                                }
                        }
                },
                "totalExtraExpenditure": {
                        "type": "object",
                        "description": "Property. range of total amount of money invoiced by the lodging establishment in extra concepts",
                        "properties": {
                                "range": {
                                        "type": "string"
                                },
                                "sortingOrder": {
                                        "type": "array",
                                        "items": {
                                                "type": "string"
                                        }
                                }
                        }
                },
                "avgDailyExpenditure": {
                        "type": "object",
                        "description": "Property. range of avg daily amount of money invoiced by the lodging establishment",
                        "properties": {
                                "range": {
                                        "type": "string"
                                },
                                "sortingOrder": {
                                        "type": "array",
                                        "items": {
                                                "type": "string"
                                        }
                                }
                        }
                },
                "avgDailyAccomodationAndBoardExpenditure": {
                        "type": "object",
                        "description": "Property. range of avg daily amount of money invoiced by the lodging establishment in accomodation and board concepts",
                        "properties": {
                                "range": {
                                        "type": "string"
                                },
                                "sortingOrder": {
                                        "type": "array",
                                        "items": {
                                                "type": "string"
                                        }
                                }
                        }
                },
                "avgDailyExtraExpenditure": {
                        "type": "object",
                        "description": "Property. range of avg daily amount of money invoiced by the lodging establishment in extra concepts",
                        "properties": {
                                "range": {
                                        "type": "string"
                                },
                                "sortingOrder": {
                                        "type": "array",
                                        "items": {
                                                "type": "string"
                                        }
                                }
                        }
                }
        }
}

=== MNXOnline/drafted_models/TouristProfile_2023_06_22_12_57/examples/example.json
{
    "id": "urn:hosp:tourpro:0001",
    "type": "TouristProfile",
    "country": "NL",
    "ageRange": {
        "range": "30-34",
        "sortingOrder": [
            "0-1",
            "2-5",
            "6-11",
            "12-17",
            "18-24",
            "25-29",
            "30-34",
            "35-39",
            "40-44",
            "45-49",
            "50-54",
            "55-59",
            "60-64",
            "65+"
        ]
    },
    "gender": "Male",
    "travelPartyComposition": "Couple",
    "lodgingType": "Resort",
    "lodgingCategory": "4 stars",
    "lodgingSize": {
        "range": "101 - 300 Medium",
        "sortingOrder": [
            "0 - 24 Very Small",
            "25 - 100 Small",
            "101 - 300 Medium",
            "301 - 700 Large",
            "701 - 1200 Very Large",
            "1201+ Massive"
        ]
    },
    "roomOfStayType": "Double",
    "board": "half-board",
    "bookingChannel": "Tour Operator",
    "reservationLeadTime": {
        "range": "91 to 120 days",
        "sortingOrder": [
            "1 to 7 Days",
            "8 to 14 Days",
            "15 to 30 Days",
            "31 to 60 Days",
            "61 to 90 Days",
            "91 to 120 Days",
            "121 to 240 Days",
            "241 to 365 Days",
            "366+ Days"
        ]
    },
    "stayLength": {
        "range": "5 to 7 days",
        "sortingOrder": [
            "1 day",
            "2 to 4 days",
            "5 to 7 days",
            "8 to 14 days",
            "15 to 21 days",
            "22+ days"
        ]
    },
    "totalExpenditure": {
        "range": "1250 to 1499 ?",
        "sortingOrder": [
            "0 to 249 ?",
            "250 to 499 ?",
            "250 to 499 ?",
            "500 to 749 ?",
            "750 to 999 ?",
            "1000 to 1499 ?",
            "1500 to 1999 ?",
            "2000 to 2999 ?",
            "3000 to 3999 ?",
            "4000 to 4999 ?",
            "5000+ ?"
        ]
    },
    "totalAccomodationAndBoardExpenditure": {
        "range": "1000 to 1249 ?",
        "sortingOrder": [
            "0 to 249 ?",
            "250 to 499 ?",
            "250 to 499 ?",
            "500 to 749 ?",
            "750 to 999 ?",
            "1000 to 1499 ?",
            "1500 to 1999 ?",
            "2000 to 2999 ?",
            "3000 to 3999 ?",
            "4000 to 4999 ?",
            "5000+ ?"
        ]
    },
    "totalExtraExpenditure": {
        "range": "0 to 249 ?",
        "sortingOrder": [
            "0 to 249 ?",
            "250 to 499 ?",
            "250 to 499 ?",
            "500 to 749 ?",
            "750 to 999 ?",
            "1000 to 1499 ?",
            "1500 to 1999 ?",
            "2000 to 2999 ?",
            "3000 to 3999 ?",
            "4000 to 4999 ?",
            "5000+ ?"
        ]
    },
    "avgDailyExpenditure": {
        "range": "200 to 249 ?",
        "sortingOrder": [
            "0 to 24 ?",
            "25 to 49 ?",
            "50 to 74 ?",
            "75 to 99 ?",
            "100 to 149 ?",
            "150 to 199 ?",
            "200 to 249 ?",
            "250 to 299 ?",
            "300 to 399 ?",
            "400 to 499 ?",
            "500 to 599 ?",
            "600+ ?"
        ]
    },
    "avgDailyAccomodationAndBoardExpenditure": {
        "range": "200 to 249 ?",
        "sortingOrder": [
            "0 to 24 ?",
            "25 to 49 ?",
            "50 to 74 ?",
            "75 to 99 ?",
            "100 to 149 ?",
            "150 to 199 ?",
            "200 to 249 ?",
            "250 to 299 ?",
            "300 to 399 ?",
            "400 to 499 ?",
            "500 to 599 ?",
            "600+ ?"
        ]
    },
    "avgDailyExtraExpenditure": {
        "range": "0 to 24 ?",
        "sortingOrder": [
            "0 to 24 ?",
            "25 to 49 ?",
            "50 to 74 ?",
            "75 to 99 ?",
            "100 to 149 ?",
            "150 to 199 ?",
            "200 to 249 ?",
            "250 to 299 ?",
            "300 to 399 ?",
            "400 to 499 ?",
            "500 to 599 ?",
            "600+ ?"
        ]
    }
}
